datasets:
  cifar100:
    name: &dataset_name 'cifar100'
    type: 'CIFAR100'
    root: &root_dir !join ['./resource/dataset/', *dataset_name]
    splits:
      dummy:
        dataset_id: '25K'
        params:
          root: *root_dir
          train: True
          download: True
        random_split:
          lengths: [0.626, 0.374]
          generator_seed: 42
          sub_splits:
            - dataset_id: &cifar100_train !join [*dataset_name, '/train']
              transform_params:
                - type: 'RandomCrop'
                  params:
                    size: 32
                    padding: 4
                - type: 'RandomHorizontalFlip'
                  params:
                    p: 0.5
                - type: 'ToTensor'
                  params:
                - &normalize
                  type: 'Normalize'
                  params:
                    mean: [0.5070754, 0.48655024, 0.44091907]
                    std: [0.26733398, 0.25643876, 0.2761503]
            - dataset_id: &cifar100_val !join [*dataset_name, '/val']
              transform_params: &val_transform
                - type: 'ToTensor'
                  params:
                - *normalize
      test:
        dataset_id: &cifar100_test !join [*dataset_name, '/test']
        params:
          root: *root_dir
          train: False
          download: True
          transform_params: *val_transform

models:
  model:
    name: &student_model_name 'resnet44'
    params:
      num_classes: 100
      pretrained: False
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name]
    ckpt: !join ['./resource/ckpt/', *dataset_name, '/ce/', *student_experiment, '-teacher-31k.pt']

train:
  log_freq: 100
  num_epochs: 200
  train_data_loader:
    dataset_id: *cifar100_train
    random_sample: True
    batch_size: 256
    num_workers: 8
    cache_output:
  val_data_loader:
    dataset_id: *cifar100_val
    random_sample: False
    batch_size: 256
    num_workers: 8
  model:
    adaptations:
    sequential: []
    wrapper: 'DistributedDataParallel'
    requires_grad: True
    frozen_modules: []
  optimizer:
    type: 'SGD'
    params:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0005
      nesterov: True
  scheduler:
    type: 'CosineAnnealingLR'
    params:
      T_max: 200
      eta_min: 0
  criterion:
    type: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        type: 'CrossEntropyLoss'
        params:
          reduction: 'mean'
      factor: 1.0
    sub_terms:

test:
  test_data_loader:
    dataset_id: *cifar100_test
    random_sample: False
    batch_size: 1
    num_workers: 16
